# Copyright (c) 2026 Hiroshi Atsuta
# SPDX-License-Identifier: GPL-3.0-only

"""M3MAN-007: the committed manual study manifest binds the approved scope and re-renders from its own record.

The manifest freezes the 186 models of the study before any arm is fitted. This
locks what was committed: the sources it binds, the approved cross product, the
ridge scales, the contractive banks, and the canonical environment every fit
identity carries. It is regenerated by ``scripts/freeze_manual_study.py``, never
hand-edited.
"""

from __future__ import annotations

import json
from collections import Counter
from typing import TYPE_CHECKING

import pytest

from arm_rc_ctrl.execution import load_execution
from arm_rc_ctrl.experiments.manual_recipes import ASSIGNMENTS, TRANSFORM_SOURCE
from arm_rc_ctrl.experiments.manual_study import (
    ARM_COUNT,
    CONFIGURATION_COUNT,
    EXPERIMENT_LABEL,
    MODEL_COUNT,
    STUDY_SCHEMA_VERSION,
    load_study,
    render_study_markdown,
    study_to_json,
)
from arm_rc_ctrl.provenance import sha256_file
from arm_rc_ctrl.repo import repository_root

if TYPE_CHECKING:
    from arm_rc_ctrl.experiments.manual_study import StudyManifest

REPO_ROOT = repository_root()
EXPERIMENT = REPO_ROOT / "docs" / "experiments" / "task_1a_manual_demonstration"
MANIFEST = EXPERIMENT / "study_manifest_v1.json"
MARKDOWN = EXPERIMENT / "study_manifest_v1.md"
PANEL = REPO_ROOT / "docs" / "experiments" / "task_1a_repeated_demonstration" / "panel_manifest_v1.json"
CANONICAL_EXECUTION = PANEL.parent / "execution_environment_v1.json"
BANK = EXPERIMENT / "bank" / "bank_v1.json"

APPROVED_TRIALS = {
    "feasible-best": 17,
    "feasible-middle": 136,
    "feasible-worst": 53,
    "failure-actual-dwell": 1,
    "failure-joint-velocity": 0,
    "failure-generated-dwell": 28,
}
"""The six inherited configurations (D5), in the panel's own label order."""

ARM_KINDS = {"S": 60, "M10": 6, "R10": 60, "C10": 60}
"""Models per arm kind over the six configurations; ``M100`` and the fixed-alpha diagnostics stay deferred (D4)."""

SEED_BANK = 1
"""The study's shared contractive seed bank."""

ENTRY_KEYS = {"arm", "configuration", "contractive", "execution_identity", "fit_identity", "source_trial", "warmup_s"}
"""Everything an entry stores: what identifies the model, never a copy of an input the header binds once."""

LARGE_FILE_LIMIT_KB = 200
"""The repository's `check-added-large-files` limit (`.pre-commit-config.yaml`); the record must stay committable."""


@pytest.fixture(scope="module")
def manifest() -> StudyManifest:
    """The committed manifest, loaded through the strict loader that re-derives every invariant."""
    return load_study(MANIFEST)


def test_committed_manifest_binds_the_approved_scope(manifest: StudyManifest) -> None:
    """186 models: the six inherited configurations crossed with the 31 arms, each identified exactly once."""
    assert manifest.experiment == EXPERIMENT_LABEL
    assert manifest.schema_version == STUDY_SCHEMA_VERSION
    assert (CONFIGURATION_COUNT, ARM_COUNT, MODEL_COUNT) == (6, 31, 186)
    assert len(manifest.entries) == MODEL_COUNT
    assert len(manifest.configurations) == CONFIGURATION_COUNT
    assert dict(Counter(entry.arm.arm for entry in manifest.entries)) == ARM_KINDS
    assert len({entry.fit_identity for entry in manifest.entries}) == MODEL_COUNT
    assert {c.label: c.source_trial for c in manifest.configurations} == APPROVED_TRIALS


def test_committed_manifest_binds_its_sources_by_digest(manifest: StudyManifest) -> None:
    """The panel and the bank are bound to the files as committed, and the transform to the scripted dataset."""
    assert manifest.panel.sha256 == sha256_file(PANEL)
    assert manifest.bank.sha256 == sha256_file(BANK)
    assert manifest.transform_source == TRANSFORM_SOURCE
    assert manifest.transform.derived_from == (TRANSFORM_SOURCE.artifact_id,)
    assert manifest.seed_bank == SEED_BANK
    assert [record.assignment for record in manifest.demonstrations] == list(ASSIGNMENTS)
    assert len({record.dataset.payload_sha256 for record in manifest.demonstrations}) == len(ASSIGNMENTS)
    assert all(record.dataset.record.startswith("data/records/processed/") for record in manifest.demonstrations)
    assert all(record.loss_rows > 0 for record in manifest.demonstrations)


def test_committed_ridge_scales_follow_the_episode_count(manifest: StudyManifest) -> None:
    """Every arm fits at ``K alpha_0``: the singleton at one episode, every matched arm at ten."""
    for entry in manifest.entries:
        accounting, esn = manifest.accounting(entry), manifest.esn(entry)
        base = accounting.base_alpha
        expected = 1 if entry.arm.arm == "S" else 10
        assert entry.episodes == expected
        assert esn.readout.alpha == expected * base  # the same multiplication the loader rebuilds
        assert accounting.solver_alpha == esn.readout.alpha
        assert esn.readout.explicit_bias
        assert not esn.readout.include_bias


def test_committed_contractive_banks_cover_the_locked_demonstrations(manifest: StudyManifest) -> None:
    """Each of the ten demonstrations grows one bank, and the ten banks are distinct witnesses."""
    banks = {e.contractive.assignment: e.contractive for e in manifest.entries if e.contractive is not None}
    assert sorted(banks) == sorted(ASSIGNMENTS)
    assert len({bank.bank_sha256 for bank in banks.values()}) == len(ASSIGNMENTS)
    assert {bank.seed_bank for bank in banks.values()} == {SEED_BANK}


def test_committed_manifest_stays_inside_the_repository_large_file_limit(manifest: StudyManifest) -> None:
    """Entries reference the header instead of embedding copies of their inputs, so the record stays committable."""
    assert MANIFEST.stat().st_size // 1024 <= LARGE_FILE_LIMIT_KB
    document = json.loads(MANIFEST.read_text(encoding="utf-8"))
    assert {key for entry in document["entries"] for key in entry} == ENTRY_KEYS
    assert [record["assignment"] for record in document["demonstrations"]] == list(ASSIGNMENTS)
    assert manifest.sources.keys() == manifest.loss_rows.keys() == set(ASSIGNMENTS)


def test_committed_manifest_is_canonical_clean_and_re_renders(manifest: StudyManifest) -> None:
    """The record re-serializes and re-renders byte for byte, from a clean non-exploratory run, with no host path."""
    assert study_to_json(manifest) + "\n" == MANIFEST.read_text(encoding="utf-8")
    assert render_study_markdown(manifest) == MARKDOWN.read_text(encoding="utf-8")
    assert manifest.provenance.project_dirty is False
    assert manifest.provenance.exploratory is False
    assert manifest.execution.policy == "p-cores"
    assert manifest.execution.canonical
    # The study must bind THE canonical environment, probed with the numerical runtimes loaded, or every fit
    # identity keys an environment no fit runs in and the numerics refuses them all (C10).
    assert manifest.execution.identity == load_execution(CANONICAL_EXECUTION).identity
    identity = manifest.execution.identity
    assert all(entry.execution_identity == identity for entry in manifest.entries)
    for text in (MANIFEST.read_text(encoding="utf-8"), MARKDOWN.read_text(encoding="utf-8")):
        assert "/home/" not in text
        assert "/mnt/" not in text
