# Copyright (c) 2026 Hiroshi Atsuta
# SPDX-License-Identifier: GPL-3.0-only

"""M3REP-008: the committed reproduction audit reproduces the committed pilot evidence completely."""

from __future__ import annotations

import json
import subprocess
from typing import cast

import pytest

from arm_rc_ctrl.config import to_mapping
from arm_rc_ctrl.experiments.repetition_report import load_report
from arm_rc_ctrl.experiments.reproduce_repetition import DECLARED_COMPARISONS, RESIMULATION_RULE, STEPS
from arm_rc_ctrl.repo import repository_root

pytestmark = pytest.mark.regression

REPO_ROOT = repository_root()
DOCS = REPO_ROOT / "docs" / "experiments" / "task_1a_repeated_demonstration"
AUDIT = DOCS / "reproduction_audit_v1.json"
AUDIT_MARKDOWN = DOCS / "reproduction_audit_v1.md"


def _audit() -> dict[str, object]:
    return cast("dict[str, object]", json.loads(AUDIT.read_text(encoding="utf-8")))


def test_audit_passed_every_step_on_the_committed_evidence() -> None:
    """Every step ran and passed from a clean checkout in the canonical environment, with zero deviation."""
    data = _audit()
    assert data["ok"] is True
    checks = cast("list[dict[str, object]]", data["checks"])
    assert [c["name"] for c in checks] == list(STEPS)
    assert all(c["ok"] is True for c in checks)
    details = {str(c["name"]): str(c["detail"]) for c in checks}
    assert not any(detail.startswith("skipped") for detail in details.values())
    assert "123 evidence pointers" in details["records"]
    assert "4790 run payloads" in details["payloads"]
    assert "156 cached fits" in details["payloads"]
    assert details["recipes"].startswith("156 prescribed fit identities")
    assert details["fits"].startswith("156 fits refitted bitwise")
    assert details["metrics"].startswith("390 replay runs and the runs of 4400 executed model pairs")
    assert "120 eligibility rows" in details["tables"]
    assert details["resimulation"].startswith("391 runs re-simulated bitwise")
    assert "34 figures and 3 animations regenerated byte-for-byte" in details["assets"]
    assert data["max_deviation"] == 0.0
    inputs = cast("dict[str, str]", data["inputs"])
    report = load_report(DOCS / "repetition_report_v1.json")
    assert inputs["evidence_project_commit"] == report.provenance.project_commit
    assert inputs["canonical_execution_identity"] == report.canonical_execution_identity
    assert inputs["reproduction_execution_identity"] == report.canonical_execution_identity
    assert inputs["reproduction_project_dirty"] == "False"
    assert inputs["c11_exception_candidate"].startswith("6912bffcc9a5")
    assert inputs["c11_exception_reference"].startswith("cc62950ed9a0")
    ancestry = subprocess.run(
        ["git", "merge-base", "--is-ancestor", inputs["reproduction_project_commit"], "HEAD"],
        check=False,
        capture_output=True,
        cwd=REPO_ROOT,
    )
    assert ancestry.returncode == 0, "the audited reproduction commit must be in this history"


def test_audit_declares_its_comparisons_rule_and_coverage() -> None:
    """The declared comparisons, the frozen subset rule, and the coverage report are recorded verbatim."""
    data = _audit()
    assert data["comparisons"] == [to_mapping(c) for c in DECLARED_COMPARISONS]
    assert data["resimulation_rule"] == RESIMULATION_RULE
    coverage = cast("dict[str, object]", data["coverage"])
    assert coverage["runs"] == 391
    assert cast("int", coverage["rc_runs"]) + cast("int", coverage["replay_runs"]) == 391
    assert coverage["formulations"] == ["absolute", "residual"]
    assert len(cast("list[str]", coverage["arms"])) == 20
    assert coverage["warmups_s"] == [0.0, 0.25, 1.0]
    assert coverage["trackers"] == ["computed_torque", "pd_v2"]
    assert set(cast("list[str]", coverage["classes"])) >= {"nominal", "posture_small", "posture_large", "force"}
    assert cast("int", coverage["first_pair_failures"]) + cast("int", coverage["later_failures"]) == 95
    unavailable = cast("list[str]", coverage["unavailable"])
    assert any(u.startswith("replay-blocked") for u in unavailable)
    assert any(u.startswith("training failures") for u in unavailable)


def test_audit_reports_doc005_apart_and_records_the_gates() -> None:
    """Both historical reruns completed with the exact-zero tolerance untouched; every gate passed."""
    data = _audit()
    reruns = cast("list[dict[str, object]]", data["doc005"])
    assert [r["label"] for r in reruns] == ["canonical-affinity", "cpus-16-31"]
    for rerun in reruns:
        assert rerun["tolerance"] == 0.0
        assert rerun["ok"] is not None
        assert "--from-evidence" in str(rerun["command"])
    canonical, e_cores = reruns
    assert canonical["ok"] is True
    assert canonical["max_deviation"] == 0.0
    assert canonical["returncode"] == 0
    assert list(cast("list[int]", canonical["cpus"])) == list(range(16))
    assert list(cast("list[int]", e_cores["cpus"])) == list(range(16, 32))
    gates = cast("list[dict[str, object]]", data["gates"])
    assert [g["command"] for g in gates] == ["uv run --locked nox", "uv run --locked nox -s pre_commit"]
    assert all(g["returncode"] == 0 for g in gates)
    text = AUDIT_MARKDOWN.read_text(encoding="utf-8")
    assert text.startswith("# Task 1-a repeated-demonstration pilot reproduction")
    assert "ok: True" in text
    assert "## Historical task 1-a reproduction (DOC-005), reported apart" in text
    assert "| canonical-affinity |" in text
    assert "| cpus-16-31 |" in text
