# Copyright (c) 2026 Hiroshi Atsuta
# SPDX-License-Identifier: GPL-3.0-only

"""M3MAN-007: the committed manual numerical validation covers the copy controls and passed every check.

The validation is the condition the plan sets before any behavioural
interpretation of the study. This locks what was committed: the scope it
covered, the checks it made, the environment every fit bound, and the fact that
nothing was accepted by precedent. It is regenerated by
``python -m arm_rc_ctrl.experiments.manual_numerics validate``, never
hand-edited.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from arm_rc_ctrl.execution import load_execution
from arm_rc_ctrl.experiments.manual_numerics import (
    LARGE_FILE_LIMIT_BYTES,
    NUMERICAL_ARMS,
    TOLERANCES,
    load_validation,
    render_validation_markdown,
    validation_to_json,
)
from arm_rc_ctrl.provenance import sha256_file
from arm_rc_ctrl.repo import repository_root

if TYPE_CHECKING:
    from arm_rc_ctrl.experiments.manual_numerics import ManualNumericalValidation

REPO_ROOT = repository_root()
EXPERIMENT = REPO_ROOT / "docs" / "experiments" / "task_1a_manual_demonstration"
VALIDATION = EXPERIMENT / "numerical_validation_v1.json"
MARKDOWN = EXPERIMENT / "numerical_validation_v1.md"
STUDY = EXPERIMENT / "study_manifest_v1.json"
CANONICAL_EXECUTION = (
    REPO_ROOT / "docs" / "experiments" / "task_1a_repeated_demonstration" / "execution_environment_v1.json"
)

N_FITS = 120
"""Six inherited configurations times the twenty singleton and duplication-control arms."""
N_COMPARISONS = 60
"""One ten-copy control against its singleton per demonstration per configuration."""


@pytest.fixture(scope="module")
def validation() -> ManualNumericalValidation:
    """The committed validation, loaded through the strict loader that re-derives every count."""
    return load_validation(VALIDATION)


def test_committed_validation_covers_the_copy_controls(validation: ManualNumericalValidation) -> None:
    """The scope is the singleton and duplication-control arms over the six inherited configurations."""
    assert validation.experiment == "task_1a_manual_v1"
    assert validation.arms == NUMERICAL_ARMS
    assert len(validation.configurations) == 6
    assert validation.n_fits == N_FITS
    assert validation.n_comparisons == N_COMPARISONS
    assert len(validation.repeat_identities) == N_COMPARISONS
    assert len(validation.fresh_refits) == N_FITS


def test_committed_validation_passed_every_check(validation: ManualNumericalValidation) -> None:
    """Comparisons, residuals, weighting, literal repetition, isolation and fresh refits all held."""
    assert validation.n_comparisons_passed == N_COMPARISONS
    assert validation.n_residuals_within == N_FITS
    assert validation.n_weighting_matches == N_FITS
    assert validation.n_repeat_identities_identical == N_COMPARISONS
    assert validation.n_fresh_refits_passed == N_FITS
    assert all(fit.training_sources_expected and fit.transform_isolated for fit in validation.fits)
    assert all(validation.probe_states_identical_across_arms.values())
    assert validation.all_passed is True


def test_committed_comparisons_pass_with_margin(validation: ManualNumericalValidation) -> None:
    """Every comparison sits well inside the prescribed tolerance, not marginally within it."""
    assert validation.tolerances == TOLERANCES
    assert TOLERANCES.prediction_atol_rad == 1e-8
    assert TOLERANCES.prediction_rtol == 1e-8
    assert TOLERANCES.residual_max == 1e-10
    worst = max(validation.comparisons, key=lambda comparison: comparison.max_abs)
    assert worst.max_abs < TOLERANCES.prediction_atol_rad / 10
    assert all(comparison.passed for comparison in validation.comparisons)
    assert all(fit.normal.within for fit in validation.fits)


def test_committed_validation_binds_the_study_and_the_canonical_environment(
    validation: ManualNumericalValidation,
) -> None:
    """The validation is bound to the frozen study as committed and to the environment fits run in."""
    assert validation.study_manifest_sha256 == sha256_file(STUDY)
    assert validation.study_manifest_file == "docs/experiments/task_1a_manual_demonstration/study_manifest_v1.json"
    assert validation.execution.identity == load_execution(CANONICAL_EXECUTION).identity
    assert validation.execution.policy == "p-cores"
    assert validation.execution.canonical


def test_committed_validation_is_clean_and_re_renders(validation: ManualNumericalValidation) -> None:
    """The record re-serializes and re-renders byte for byte, from a clean run, inside the committable size."""
    text = VALIDATION.read_text(encoding="utf-8")
    assert validation_to_json(validation) + "\n" == text
    assert render_validation_markdown(validation) == MARKDOWN.read_text(encoding="utf-8")
    assert validation.provenance.project_dirty is False
    assert validation.provenance.exploratory is False
    assert len(text.encode("utf-8")) <= LARGE_FILE_LIMIT_BYTES
    for rendered in (text, MARKDOWN.read_text(encoding="utf-8")):
        assert "/home/" not in rendered
        assert "/mnt/" not in rendered
